name: PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Last merge
        run: |
          LAST_MERGE=$(git log --merges --pretty=format:"%H" origin/main..origin/dev | head -n 1)
          echo "LAST_MERGE=$LAST_MERGE" >> $GITHUB_ENV
      
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npm run type-check || npm run tsc || echo "Executando verificação de tipos TypeScript"

      - name: Build Next.js application
        run: npm run build

      - name: Get last commit message
        id: get-commit-message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" ${{ env.LAST_MERGE }})
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Promoção Dev para Main"
          title: "🚀 Promoção Dev para Main ${{ steps.jira_tickets.outputs.tickets }}"
          body: |
            ## Solicitação de Promoção para Produção

            Este PR foi gerado automaticamente para promover as alterações da branch Dev para Main.

            ### 🔄 Alterações Incluídas
            ${{ steps.get_changes.outputs.changes }}

            ### ✅ Verificações
            - [x] Build Next.js executado com sucesso
            - [x] Verificação de tipos TypeScript
            - [x] Testes unitários executados
            - [ ] Revisão de código necessária
            - [ ] Testes em ambiente de homologação realizados

            ### 📋 Notas Adicionais
            - Certifique-se de revisar todas as alterações antes de mesclar.
            - Após a mesclagem, monitore o ambiente de produção para quaisquer problemas.
          base: main
          branch: promote-dev-to-main
          labels: |
            promotion
            automated
            needs-review
            next-js
